---
title: "R Notebook"
output: html_notebook
---

```{r}
whole_seq <- read.csv(file = 'whole_seq_stats.csv')
whole_seq <- subset(whole_seq, Age!='BabyBoomers')
whole_seq <- subset(whole_seq, Age!='Traditionalists')
```

```{r}
genx <- subset(whole_seq, Age == 'GenX')
genx

geny <- subset(whole_seq, Age == 'GenY')
geny

genz <- subset(whole_seq, Age == 'GenZ')
genz

male <- subset(whole_seq, Gender == 'Male')
male

fem <- subset(whole_seq, Gender == 'Female')
fem
```

```{r}
# Boxplots for repeated sequence frequency across age groups.
par(mar=c(7,5,1,1), mfrow = c(1, 2))
boxplot(Elipse.Count ~ Age, data = whole_seq, outline = FALSE, las = 2, xlab = 'Generation', ylab = 'Ellipse Count')
boxplot(Exclaimation.Seq.Count ~ Age, data = whole_seq, outline = FALSE, las = 2, xlab = 'Generation', ylab = 'Exclaimation Sequence Count')
```


```{r}
# Boxplots for repeated sequence frequency across genders.
par(mar=c(7,5,1,1), mfrow = c(1, 2))
boxplot(Elipse.Count ~ Gender, data = whole_seq, outline = FALSE, xlab = 'Gender', ylab = 'Ellipse Count')
boxplot(Exclaimation.Seq.Count ~ Gender, data = whole_seq, outline = FALSE, xlab = 'Gender', ylab = 'Exclaimation Sequence Count')
```

```{r}
# Boxplots for ellipse frequency for each gender ACROSS GENERATIONS.
par(mar=c(7,5,1,1), mfrow = c(1,3))
boxplot(Elipse.Count ~ Gender, data = genx, outline = FALSE, las = 1, xlab = 'Gender within Gen X', ylab = 'Ellipse Count')
boxplot(Elipse.Count ~ Gender, data = geny, outline = FALSE, las = 1, xlab = 'Gender within Gen Y', ylab = 'Ellipse Count')
boxplot(Elipse.Count ~ Gender, data = genz, outline = FALSE, las = 1, xlab = 'Gender within Gen Z', ylab = 'Ellipse Count')
```

```{r}
# Boxplots for exclaimation seq frequency for each gender ACROSS GENERATIONS.
par(mar=c(7,5,1,1), mfrow = c(1,3))
boxplot(Exclaimation.Seq.Count ~ Gender, data = genx, outline = FALSE, las = 1, xlab = 'Gender within Gen X', ylab = 'Exclaimation Sequence Count')
boxplot(Exclaimation.Seq.Count ~ Gender, data = geny, outline = FALSE, las = 1, xlab = 'Gender within Gen Y', ylab = 'Exclaimation Sequence Count')
boxplot(Exclaimation.Seq.Count ~ Gender, data = genz, outline = FALSE, las = 1, xlab = 'Gender within Gen Z', ylab = 'Exclaimation Sequence Count')
```

